version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack-prod
artifacts:
  files:
    - index.html
    - favicon.ico
    - cv-max-aldunate-2018-02.pdf
    - styles/main.css
    - images/*
    - practices/*
    - dist/bundle.js